name    'counsyl-sys'
version '0.9.14'
source  'git://github.com/counsyl/puppet-sys.git'
author  'Counsyl, Inc.'
license 'Apache License, Version 2.0'
summary 'Common platform packages, resources and modules'
description  'Common platform packages, resources and modules'
project_page 'https://github.com/counsyl/puppet-sys'

dependency 'puppetlabs/stdlib', '>= 4.1.0'
